/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--bg-color)',
        surface: 'var(--surface-color)',
        'surface-dim': 'var(--surface-dim-color)',
        'surface-bright': 'var(--surface-bright-color)',
        'surface-container-lowest': 'var(--surface-container-lowest-color)',
        'surface-container-low': 'var(--surface-container-low-color)',
        'surface-container': 'var(--surface-container-color)',
        'surface-container-high': 'var(--surface-container-high-color)',
        'surface-container-highest': 'var(--surface-container-highest-color)',
        'on-surface': 'var(--on-surface-color)',
        'on-surface-variant': 'var(--on-surface-variant-color)',
        outline: 'var(--outline-color)',
        'outline-variant': 'var(--outline-variant-color)',
        primary: 'var(--primary-color)',
        'on-primary': 'var(--on-primary-color)',
        'primary-container': 'var(--primary-container-color)',
        'on-primary-container': 'var(--on-primary-container-color)',
        secondary: 'var(--secondary-color)',
        'secondary-container': 'var(--secondary-container-color)',
        'on-secondary-container': 'var(--on-secondary-container-color)',
        tertiary: 'var(--tertiary-color)',
        'tertiary-container': 'var(--tertiary-container-color)',
        'on-tertiary-container': 'var(--on-tertiary-container-color)',
        'tertiary-fixed': '#ffddb2',
        'tertiary-fixed-dim': '#ffb95e',
        'on-tertiary-fixed-variant': '#683d00',
        error: 'var(--error-color)',
        'error-container': 'var(--error-container-color)',
        'on-error-container': 'var(--on-error-container-color)',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        tight: ['Inter Tight', 'Inter', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
        display: ['Inter Tight', 'Inter', 'sans-serif'],
        label: ['Inter Tight', 'Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['5.5rem', { lineHeight: '1', letterSpacing: '-0.04em' }],
        'display-md': ['4.25rem', { lineHeight: '1', letterSpacing: '-0.035em' }],
        'headline-lg': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.025em' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'headline-md': ['1.25rem', { lineHeight: '1.3', letterSpacing: '-0.015em' }],
        'body-lg': ['1rem', { lineHeight: '1.6', letterSpacing: '-0.01em' }],
        'body-md': ['0.875rem', { lineHeight: '1.5' }],
        'label-caps': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.08em' }],
      },
      spacing: {
        'gutter': '1.5rem',
        'container-padding-mobile': '1rem',
        'container-padding-desktop': '2rem',
        'section-gap': '3.5rem',
      },
      borderRadius: {
        '3xl': '1.5rem',
      }
    },
  },
  plugins: [],
}
