/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#F7F8F6',
        surface: '#ffffff',
        'surface-dim': '#edeef1',
        'surface-bright': '#f9f9fd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f7',
        'surface-container': '#edeef1',
        'surface-container-high': '#e7e8eb',
        'surface-container-highest': '#e1e2e5',
        'on-surface': '#191c1f',
        'on-surface-variant': '#41474e',
        outline: '#72787f',
        'outline-variant': '#c1c7cf',
        primary: '#2a6088',
        'on-primary': '#ffffff',
        'primary-container': '#4679a2',
        'on-primary-container': '#ffffff',
        secondary: '#51606f',
        'secondary-container': '#d8e4ec',
        'on-secondary-container': '#3a4856',
        tertiary: '#66586b',
        'tertiary-container': '#eddcf2',
        'on-tertiary-container': '#4e4153',
        'tertiary-fixed': '#ffddb2',
        'tertiary-fixed-dim': '#ffb95e',
        'on-tertiary-fixed-variant': '#683d00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        tight: ['Inter Tight', 'Inter', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
        display: ['Inter Tight', 'Inter', 'sans-serif'],
        label: ['Inter Tight', 'Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['5.5rem', { lineHeight: '1', letterSpacing: '-0.04em' }],
        'display-md': ['4.25rem', { lineHeight: '1', letterSpacing: '-0.035em' }],
        'headline-lg': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.025em' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'headline-md': ['1.25rem', { lineHeight: '1.3', letterSpacing: '-0.015em' }],
        'body-lg': ['1rem', { lineHeight: '1.6', letterSpacing: '-0.01em' }],
        'body-md': ['0.875rem', { lineHeight: '1.5' }],
        'label-caps': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.08em' }],
      },
      spacing: {
        'gutter': '1.5rem',
        'container-padding-mobile': '1rem',
        'container-padding-desktop': '2rem',
        'section-gap': '3.5rem',
      },
      borderRadius: {
        '3xl': '1.5rem',
      }
    },
  },
  plugins: [],
}
